scope: pgsql
namespace: /cluster/
name: pg2

restapi:
  listen: pg2:8008
  connect_address: pg2:8008

etcd3:
  hosts: etcd:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 5
        max_replication_slots: 5
        wal_keep_segments: 128
        checkpoint_timeout: 30

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication postgres 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5

  users:
    postgres:
      password: postgres

postgresql:
  listen: pg2:5432
  connect_address: pg2:5432
  data_dir: /data/patroni
  bin_dir: /usr/lib/postgresql/17.2/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: postgres
      password: postgres
    superuser:
      username: postgres
      password: postgres
  create_replica_methods:
    basebackup:
      checkpoint: 'fast'
  parameters:
    unix_socket_directories: '.'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
